<?php
session_start();
require_once 'login.php';
include 'redir.php';
echo <<<_HEAD1
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="style/simple.css">
  <title>CompLib: Documentation</title>
</head>
<body>
_HEAD1;
include 'menuf.php';
echo <<<_MAIN1
<h2>Documentation</h2>
This website is based on a MySQL database consisting of 4 tables. Those tables are:<br>

<ul>
<li>Manufacturer table</li>
<p> This table has the name of each supplier that manufactured the compounds in this database. Each manufacturer is given an ID from 1-5. 
</p>
<li>Compounds table</li>
<p>This table holds an entry for each compound. In addition to the compound name and a reference to the manufacturer table for each compound, it also holds details about the chemical composition and some basic physical properties for each compound.
</p>
<li>SMILES table</li>
<p>This table holds a reference to the compounds table and a SMILES string of each compound.
</p>
<li>Molecules table</li>
<p>This table holds a reference to the compounds table and encoded details about each compound.
</p>
</ul>

These tables are formally defined as relational tables, with a common compound ID that allows for a table to be mapped to another table. 
<p> 


<details>
<summary>Data extraction</summary>
<p> The data for these tables was extracted from a master sdf file containing all the entries of the compound from all manufacturers. A combination of Python scripts and Java programs were used to generate additional properties for each compound, or to parse each data into the relational database. 
</details>

<details>
<summary>Page linkage</summary>
<p> The website uses php sessions to link the pages. Overall the structure of the website is of a master login page, coupled to an index page. from this index page there are hyperlinks to 12 functional pages. Each page includes a mechanism to detect if a current session is still valid and a redirect to the master login page if no valid session is found. Each page also includes a single menu page allowing access to each of the other pages. Several pages which require database access also use a script containing all the necessary functions to simplify the code in each page. A footer section is also included in all pages.
</details>


<h2>Page functions</h2>
Following is a description of the function of each page:
<br>
<details>
<summary>Summary</summary>
<p>This page summarizes the minimum, maximum, and average number of carbon, oxygen, and nitrogen atoms for each supplier. It also shows the corresponding Manufacturer ID for each supplier. The average and min/max count is retrieved from a MySQL query ran by the PHP code.</p>
</details>

<details>
<summary>List by Supplier</summary>
<p>This page allows user to view the list of compounds for each manufacturer and their attributes. Only one manufacturer can be selected at a time. The output table can be sorted by clicking on the header columns.</p>
</details>

<details>
<summary>Select Suppliers</summary>
<p>This page allows user to mask certain suppliers to narrow down searches in the "Search by" pages. Must be preselected before searching for compounds by element or by property. User can select multiple suppliers or just one supplier at a time.</p>
</details>

<details>
<summary>Search by element</summary>
<p>This page allows user to search the catalogue by the number of atoms, or by number of C/N/O. The supplier selection in the Select Suppliers page will apply here. A list of compound IDs is returned, and clicking on the compound ID will show the properties of the compound.</p>
</details>

<details>
<summary>Search by property</summary>
<p>This page allows user to search the catalogue by the molecular weight, TPSA, or XlogP properties. User is advised to use the Histogram page to check the suitable values for the input. Supplier mask does not apply in this search. A list of compound ID with Manufacturer name and the value of the Property searched for is returned. Clicking on the compound ID will show the properties of the compound.
</p>
</details>

<details>
<summary>SMILES to Spectra</summary>
<p>This page allows the user to search by element and returns the compound ID, manufacturer, and a SMILES string for each compound. The molecular structure for each compound is generated by the NIH Cactus application which converts the SMILES string into an image in real time.
</p>
<p>Clicking on the SMILES string will automatically input the string into a JSME molecule editor that is synced with JSV spectra viewer. The molecular structure of the SMILES input is drawn and a predicted spectra of the compound is generated. Both components can be edited per user direction, or refresh the page to reset the applications to show the original compound.
</p>
<p>Credits for this Javascript implementation goes to:
<br>
<a href=http://jsmol.sourceforge.net/>Page development by Bob Hanson</a>
<br>
<a href=http://peter-ertl.com/jsme/>JSME</a>: Peter Ertl, Bruno Bienfait
<br>
<a href=http://jspecview.sourceforge.net>JSpecView</a>: Robert Lancashire, Bob Hanson
<br>
<a href=http://www.nmrdb.org>nmrdb</a>: Luc Patiny
<br>
<a href=http://cactus.nci.nih.gov>NIH Resolver</a>: Markus Sitzmann
<br>
<a href=https://code.google.com/p/java2script>Java2Script</a>: Zhou Renjian
</details>

<details>
<summary>JSmol</summary>
<p>This page allows user to search the compound by its catalog ID and must match with its manufacturer. A Jsmol object is returned, which depicts a 3D representation of the compound. This applet is interactive can be the compound can be viewed multiple ways by right-clicking on the object.</p>
</details>

<details>
<summary>Statistics page</summary>
<p>This page shows the statistics (average and standard deviation) of each attribute or property for ALL compounds in the database.</p>
</details>

<details>
<summary>Histogram page</summary>
<p>This page shows the distribution of each attribute or property for ALL compounds in the database using a histogram. The histogram is generated by a Python script which plots the properties.</p>
</details>

<details>
<summary>Correlations page</summary>
<p>This page allows user to compare two attributes or properties for all compounds. The calculation used is Pearson's Correlation Coefficient. For example, number of atoms compared to itself will result in value of 1, which is a perfect correlation. The lower the value (approaching 0) shows less correlation between the two properties.</p>
</details>

<details>
<summary>Documentation (this) page</summary>
<p>This page shows the main functions of the website and credits for external applications used within the website.</p>
</details>

<details>
<summary>Exit page</summary>
<p>This logs the user out of the current session. Clicking on any links will redirect user back to the Welcome page to start a new session.</p>
</details>


<h2>Style</h2>
<p>Stylistically this website is controlled by one master cascading style sheet "Simple.css". This stylesheet utilizes native HTML elements and is minimal in appearance to ease navigation. The Welcome and Exit page uses inline style elements separate from the main website for style purposes.
<p>The tables generated from a query uses the basic css from a <a href="https://www.datatables.net/">JQuery dataTables function</a> which can be sorted and searched for its contents. Due to the large number of compounds in the <i>List Supplier</i> page, the table sorting function will only load once all the compounds have been retrieved.

<h2>Updates</h2>
<p>Documentation: <i>Updated: 29/03/2022</i>
<p>Database: <i>Updated: 24/03/2022</i>
_MAIN1;
include 'footer.php';
echo <<<_TAIL1
</body>
</html>
_TAIL1;
?>
